spring:
  application:
    name: openai-api-server
  mvc:
    async:
      request-timeout: 600000
  session:
    store-type: none
    timeout: 10800000
  datasource:
    url: "jdbc:sqlite:${SQLITE_FILE}"
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.community.dialect.SQLiteDialect

openai:
  apiKey: ${OPENAI_API_KEY:}
  model: ${OPENAI_MODEL:gpt-3.5-turbo}
  temperature: ${OPENAI_TEMPERATURE:1}
  maxTokens: ${OPENAI_MAX_TOKENS:2048}
  reduceToken: ${OPENAI_REDUCE_TOKEN:true}
  timeout:
    connect: ${OPENAI_TIMEOUT_CONNECT:180}
    read: ${OPENAI_TIMEOUT_READ:180}
    write: ${OPENAI_TIMEOUT_WRITE:180}
  apiServer:
    schema: ${OPENAI_SERVER_SCHEMA:https}
    host: ${OPENAI_SERVER_HOST:api.openai.com}
    port: ${OPENAI_SERVER_PORT:443}
    basePath: ${OPENAI_SERVER_BASE_PATH:v1}
  proxy:
    type: ${OPENAI_PROXY_TYPE:}
    host: ${OPENAI_PROXY_HOST:}
    port: ${OPENAI_PROXY_PORT:}
    user: ${OPENAI_PROXY_USER:}
    pass: ${OPENAI_PROXY_PASS:}
  chatTitle:
    prompt: "${OPENAI_CHAT_TITLE_PROMPT:请用十个以内的汉字描述一下我们谈话的主题，回答中不要带有任何标点符号！}"
app:
  serverUrl: ${SERVER_URL:http://localhost:8080}
  admin:
    user: "${ADMIN_USER:admin}"
    pass: "${ADMIN_PASS:}"
  token:
    expire-days: ${TOKEN_EXPIRE_DAYS:10}
    key: "${TOKEN_AES_KEY:WDa5x1+/y3NagFX22jcUsQ==}"

