spring:
  application:
    name: openai-api-server
  mvc:
    async:
      request-timeout: 600000
  session:
    store-type: none
    timeout: 10800000
  datasource:
    url: "jdbc:sqlite:${SQLITE_FILE}"
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.community.dialect.SQLiteDialect

openai:
  apiKey: ${OPENAI_API_KEY:}
  model: ${OPENAI_MODEL:gpt-3.5-turbo}
  temperature: ${OPENAI_TEMPERATURE:1}
  maxTokens: ${OPENAI_MAX_TOKENS:2048}
  reduceToken: ${OPENAI_REDUCE_TOKEN:false}
  timeout:
    connect: ${OPENAI_TIMEOUT_CONNECT:180}
    read: ${OPENAI_TIMEOUT_READ:180}
    write: ${OPENAI_TIMEOUT_WRITE:180}
  apiServer:
    schema: ${OPENAI_SERVER_SCHEMA:https}
    host: ${OPENAI_SERVER_HOST:api.openai.com}
    port: ${OPENAI_SERVER_PORT:443}
    basePath: ${OPENAI_SERVER_BASE_PATH:v1}
  proxy:
    type: ${OPENAI_PROXY_TYPE:}
    host: ${OPENAI_PROXY_HOST:}
    port: ${OPENAI_PROXY_PORT:}
    user: ${OPENAI_PROXY_USER:}
    pass: ${OPENAI_PROXY_PASS:}
  chatTitle:
    prompt: "${OPENAI_CHAT_TITLE_PROMPT:Please generate a four to five word title summarizing our conversation without any lead-in, punctuation, quotation marks, periods, symbols, or additional text. Remove enclosing quotation marks.}"
  defaultPrompt: "${OPENAI_DEFAULT_PROMPT:}"
app:
  serverUrl: ${SERVER_URL:http://localhost:8080}
  title: "${APP_TITLE:ChatGPT}"
  version: "${APP_VERSION:Beta}"
  admin:
    user: "${ADMIN_USER:admin}"
    pass: "${ADMIN_PASS:}"
  token:
    expire-days: ${TOKEN_EXPIRE_DAYS:10}
    key: "${TOKEN_AES_KEY:WDa5x1+/y3NagFX22jcUsQ==}"
  useWatermark: ${USE_WATERMARK:false}
  login:
    retry:
      limit: ${LOGIN_RETRY_LIMIT:5}
      freeze: ${LOGIN_RETRY_FREEZE:300}

